version: '2'
services:
  php:
    image: procoders/docker-php-fpm:7
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  nginx:
    image: jguyomard/laravel-nginx:1.13
    volumes_from:
      - php
    ports:
      - 8000:80

  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
        - 23306:3306

  intvoice-packages:
    image: innolend/gulp-bower:1.0
    working_dir: /opt/project
    volumes:
      - ./:/opt/project

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes

volumes:
  mysqldata:
  pgsqldata:
